CREATE TABLE user_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    description TEXT NOT NULL,
    date_commented TIMESTAMP DEFAULT now() NOT NULL,
    posts_id INTEGER
        REFERENCES user_posts(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES user_accounts(id) ON DELETE CASCADE NOT NULL    
);
