CREATE TABLE user_likes(
	likes_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	posts_id INTEGER
        REFERENCES user_posts(id) ON DELETE CASCADE ,
    user_id INTEGER
        REFERENCES user_accounts(id) ON DELETE CASCADE  
);