CREATE TABLE user_followers(
	follow_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id INTEGER 
        REFERENCES user_accounts(id) ON DELETE CASCADE,
        follower_id INTEGER
        REFERENCES user_accounts(id) ON DELETE CASCADE  
);